# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 0 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install flake8-quotes
    - uses: isort/isort-action@master
      with:
        configuration: "--check-only --profile black"

    - uses: psf/black@stable
      with:
        options: "--check --verbose --skip-string-normalization --line-length 120"

    - name: flake8
      run: |
        # --per-file-ignores="__init__.py:F401"
        # Ignore F401 '.counter.LineCounter' imported but unused in __init__.py
        flake8 --count --max-line-length 120 --show-source --inline-quotes 'single' --statistics --per-file-ignores="__init__.py:F401, conftest.py:F401" .
